services:
  db:
    image: postgres:15-alpine
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - cpm_network

  app:
    extends:
      file: common.yml
      service: app-base
    build:
      context: ./services
      dockerfile: Dockerfile

  app-base:
    restart: on-failure:10
    networks:
      - cpm_network
    environment:
      - ConnectionString=Host=${INVENTORY_DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
