services:
  # web:
  #   container_name: cpm_nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/configuration:/etc/nginx/configuration
  #     - ./nginx/letsencrypt:/etc/nginx/letsencrypt
  #     - ./nginx/templates:/etc/nginx/templates
  #   ports:
  #     - "80:80"
  #   networks:
  #     - cpm_network
  #   command: ["/bin/sh", "-c", "/start-nginx.sh"]
  #   # image: nginx
  #   # volumes:
  #   #   - ./nginx/templates:/etc/nginx/templates
  #   # ports:
  #   #   - "80:80"
  #   # networks:
  #   #   - cpm_network
  #   depends_on:
  #     - keycloak
  #     - idp_service

  keycloak_db:
    container_name: "keycloak_db"
    extends:
      file: common_db.yaml
      service: master_db
    ports:
      - "3005:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - cpm_network

  keycloak:
    container_name: cpm_keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]  
    ports:  
      - 3000:8080
    environment:
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HTTP_ENABLED=true
      - REDIRECT_SOCKET=proxy-https
      - KEYCLOAK_ADMIN=admin  
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres  
      - KC_DB_USERNAME=${DB_USER}  
      - KC_DB_PASSWORD=${DB_PASSWORD}  
      - KC_DB_URL=jdbc:postgresql://keycloak_db:${DB_PORT}/${DB_NAME}
    networks:  
      - cpm_network

  # cpm_ui:
  #   container_name: cpm_ui
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #     args:
  #       - AUTH_SECRET="gbBL1r2qFJ80R+/BQdWqe5McYyU52P4DrLnOqbQy580=" # Added by `npx auth`. Read more: https://cli.authjs.dev
  #       - AUTH_KEYCLOAK_ID=security-admin-console
  #       - AUTH_KEYCLOAK_SECRET=VYumVR2aR7gtMDRASsLjWrxGhcasHMMH
  #       - AUTH_KEYCLOAK_ISSUER=http://192.168.49.2:31284/realms/cpm
  #       - NEXTAUTH_URL=http://192.168.49.2:31483/
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - cpm_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "3001:5672"       # AMQP (RabbitMQ protocol)
      - "3002:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cpm_network

  api_gateway:
    container_name: cpm_api_gateway
    build:
      context: ./services
      dockerfile: Dockerfile.Gateway
    ports:
      - 3003:8080
    networks:
      - cpm_network
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      AllowedHosts: "*"
      Keycloak__realm: cpm
      Keycloak__auth-server-url: http://${LOCALHOST_IP}:3000
      Keycloak__ssl-required: none
      Keycloak__resource: security-admin-console
      Keycloak__verify-token-audience: false
      Keycloak__credentials__secret: AQxvxHNXn9RFvtB9HYq2BYcgU3Njh9bt
      Keycloak__confidential-port: 0
      Keycloak__DefaultPassword: "123"
    depends_on:
      - idp_service

networks:
  cpm_network:
    name: cpm_network
    external: true

volumes:
  postgres_keycloak_data:
  rabbitmq_data: