services:
  # web:
  #   container_name: cpm_nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/configuration:/etc/nginx/configuration
  #     - ./nginx/letsencrypt:/etc/nginx/letsencrypt
  #     - ./nginx/templates:/etc/nginx/templates
  #   ports:
  #     - "80:80"
  #   networks:
  #     - cpm_network
  #   command: ["/bin/sh", "-c", "/start-nginx.sh"]
  #   # image: nginx
  #   # volumes:
  #   #   - ./nginx/templates:/etc/nginx/templates
  #   # ports:
  #   #   - "80:80"
  #   # networks:
  #   #   - cpm_network
  #   depends_on:
  #     - keycloak
  #     - idp_service

  keycloak:
    container_name: cpm_keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]  
    ports:  
      - 8080:8080
    environment:
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HTTP_ENABLED=true
      - REDIRECT_SOCKET=proxy-https
      - KEYCLOAK_ADMIN=admin  
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres  
      - KC_DB_USERNAME=${DB_USER}  
      - KC_DB_PASSWORD=${DB_PASSWORD}  
      - KC_DB_URL=jdbc:postgresql://192.168.1.6:5432/keycloak
    networks:  
      - cpm_network

  idp_service:
    container_name: cpm_idp_service
    build:
      context: ./services
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=Identity
        # - Keycloak__realm=cpm
        # - Keycloak__auth-server-url=http://192.168.49.2:31284
        # - Keycloak__ssl-required=none
        # - Keycloak__resource=security-admin-console
        # - Keycloak__verify-token-audience=false
        # - Keycloak__credentials__secret=s6FokfrwAUixEVjzTHMBoBFxNF3niwva
        # - Keycloak__confidential-port=0
    ports:
      - "3000:8080"
    networks:
      - cpm_network
    environment:
      - SERVICE_NAME=Identity
      - Keycloak__realm=cpm
      - Keycloak__auth-server-url=http://192.168.1.6:8080
      - Keycloak__ssl-required=none
      - Keycloak__resource=security-admin-console
      - Keycloak__verify-token-audience=false
      - Keycloak__credentials__secret=s6FokfrwAUixEVjzTHMBoBFxNF3niwva
      - Keycloak__confidential-port=0

  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
    - cpm_network

#   ui:
#     build:
#       context: ./ui
#       dockerfile: Dockerfile
#       args:
#         - AUTH_SECRET="gbBL1r2qFJ80R+/BQdWqe5McYyU52P4DrLnOqbQy580=" # Added by `npx auth`. Read more: https://cli.authjs.dev
#         - AUTH_KEYCLOAK_ID=security-admin-console
#         # - AUTH_KEYCLOAK_SECRET=s6FokfrwAUixEVjzTHMBoBFxNF3niwva
#         - AUTH_KEYCLOAK_SECRET=VYumVR2aR7gtMDRASsLjWrxGhcasHMMH
#         # - AUTH_KEYCLOAK_ISSUER=http://192.168.1.6:8080/realms/cpm
#         - AUTH_KEYCLOAK_ISSUER=http://192.168.49.2:31284/realms/cpm
#         - NEXTAUTH_URL=http://192.168.49.2:31483/
#     container_name: cpm_ui
#     ports:
#       - "3001:3000"
#     networks:
#       - cpm_network

networks:
  cpm_network:
    driver: bridge

volumes:
  postgres_keycloak_data: