// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20250330163156_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f07f3b97-6e81-c702-8dc2-393942fffb50"),
                            Email = "Candido.Friesen7@gmail.com",
                            FirstName = "Tremayne",
                            LastName = "McCullough",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d95846f2-a0a3-d02c-ae24-859849f225eb"),
                            Email = "Adrian_Heathcote@hotmail.com",
                            FirstName = "Pink",
                            LastName = "Berge",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("7166cc5e-f488-0394-22b2-8e28aaedea22"),
                            Email = "Garrett.Abbott@hotmail.com",
                            FirstName = "Filomena",
                            LastName = "Beatty",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("bce5aef2-aa63-281d-f148-7ad63aba47ba"),
                            Email = "Logan24@hotmail.com",
                            FirstName = "Kaley",
                            LastName = "Blick",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("b6a6b15c-7a36-a79a-87ae-7eda0ed89f78"),
                            Email = "Odell.Marvin88@yahoo.com",
                            FirstName = "Guiseppe",
                            LastName = "Kub",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("40f349d9-54ae-6df6-9a5f-b10366f176ae"),
                            Email = "Keira.Ortiz27@gmail.com",
                            FirstName = "Melyna",
                            LastName = "Bradtke",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("dfc4fc00-48d8-54c9-945c-30a667d85988"),
                            Email = "Alexander_Grimes40@hotmail.com",
                            FirstName = "Hailey",
                            LastName = "Bauch",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("165cc49f-2eb5-1090-41ae-58318ec217e8"),
                            Email = "Jessica_Hickle@yahoo.com",
                            FirstName = "Chaim",
                            LastName = "DuBuque",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("403700b3-8af5-87d2-032b-38846c3ddf2e"),
                            Email = "Verda36@gmail.com",
                            FirstName = "Reynold",
                            LastName = "Feeney",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("5bc50560-7be1-33ac-4d2a-63b4f7501bb7"),
                            Email = "Crawford96@hotmail.com",
                            FirstName = "Filomena",
                            LastName = "Kulas",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("71a565f3-4d46-5c30-2286-dfefc576a688"),
                            Email = "Perry96@gmail.com",
                            FirstName = "Lysanne",
                            LastName = "Dicki",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("304e6d7a-7b29-cd27-8a53-687bd53aec00"),
                            Email = "Nyasia98@gmail.com",
                            FirstName = "Josiane",
                            LastName = "Kuhn",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("84e3a52b-395c-c898-2e55-f7d9fe0033a7"),
                            Email = "Abel59@hotmail.com",
                            FirstName = "Sarai",
                            LastName = "Krajcik",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("d3473619-c598-4fde-7be8-048497a37150"),
                            Email = "Eva.Kilback10@hotmail.com",
                            FirstName = "Cheyanne",
                            LastName = "Lehner",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("c55e12eb-5780-f200-9f6a-25f1c4306877"),
                            Email = "Rhianna.DAmore@hotmail.com",
                            FirstName = "Sally",
                            LastName = "Raynor",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("de6db714-0132-3506-4eff-acb37f89fa90"),
                            Email = "Joesph_Block@yahoo.com",
                            FirstName = "Charlotte",
                            LastName = "Waelchi",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("b59b08e3-fdeb-db24-56be-b0c9ea21c09d"),
                            Email = "Reilly96@gmail.com",
                            FirstName = "Dominic",
                            LastName = "Turner",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("1df68562-8317-b555-c1fd-fa2965514a50"),
                            Email = "Murray.Rohan@yahoo.com",
                            FirstName = "Leda",
                            LastName = "Breitenberg",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("5bd45ad1-30bc-2eeb-107d-52650706c3d3"),
                            Email = "Cayla16@hotmail.com",
                            FirstName = "Candelario",
                            LastName = "O'Hara",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("b3e952a5-3658-3146-df14-4cbdaef9f990"),
                            Email = "Emmanuelle_Hodkiewicz9@yahoo.com",
                            FirstName = "Hudson",
                            LastName = "Senger",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("29dd5889-bbb8-223b-c1b6-694638d5da36"),
                            Email = "Elwyn_Stroman@hotmail.com",
                            FirstName = "Marta",
                            LastName = "Emard",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("7c5adb77-134e-09c0-14a6-cfdd68072658"),
                            Email = "Jamal_Grimes57@gmail.com",
                            FirstName = "Marcos",
                            LastName = "Jones",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("565edeb1-061a-e964-dbb2-dc60bed4adf6"),
                            Email = "Ana.Grant@yahoo.com",
                            FirstName = "Vincent",
                            LastName = "Cremin",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("376ca99a-712c-032d-643d-9c3561b2faa0"),
                            Email = "Dexter_Heidenreich@hotmail.com",
                            FirstName = "Serenity",
                            LastName = "Nienow",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("172f4c3f-ef46-e342-c4fe-bc71992dbd69"),
                            Email = "Kylie.Haley65@yahoo.com",
                            FirstName = "Flo",
                            LastName = "Boyer",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("40089bf2-16c3-56a2-a5f7-df4216bc74fa"),
                            Email = "Amie22@hotmail.com",
                            FirstName = "Duncan",
                            LastName = "Marquardt",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("fb70d123-8fd1-b6c8-81df-54533aa301e8"),
                            Email = "Koby.Feeney@hotmail.com",
                            FirstName = "Maryse",
                            LastName = "Bednar",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("067e8687-b733-ebae-5ed1-1df2a6a68416"),
                            Email = "Adrian_Beer@yahoo.com",
                            FirstName = "Maxine",
                            LastName = "Donnelly",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("6edc796f-0812-fb59-6353-734b10c183c9"),
                            Email = "Lonie.Mills@yahoo.com",
                            FirstName = "Orlo",
                            LastName = "Runolfsdottir",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("b405dd95-3766-66b4-c568-96b9db3fd956"),
                            Email = "Kraig_Hirthe15@gmail.com",
                            FirstName = "Merle",
                            LastName = "Cronin",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("2bff04f7-8f56-3661-69d8-3402a5952b9f"),
                            Email = "Rosalee.Wunsch@hotmail.com",
                            FirstName = "Marjory",
                            LastName = "Sauer",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("7f64f29f-40f0-d75c-970f-6e32b43b6fd9"),
                            Email = "Wilford.Lakin99@hotmail.com",
                            FirstName = "Kody",
                            LastName = "Littel",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("5db326b3-da43-130a-708b-642ae146287c"),
                            Email = "Julianne72@yahoo.com",
                            FirstName = "Roger",
                            LastName = "Wiza",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("7b47f4ce-e98a-204b-d71b-3c1aa97a5434"),
                            Email = "Letitia75@hotmail.com",
                            FirstName = "Luigi",
                            LastName = "Crist",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("e948ea49-663a-c86b-559c-8f4e938e8887"),
                            Email = "Mitchell10@yahoo.com",
                            FirstName = "Seth",
                            LastName = "Brekke",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("d9c16216-20a7-1f0b-a00a-31a0a061e571"),
                            Email = "Quinn.Zboncak@gmail.com",
                            FirstName = "Kory",
                            LastName = "Kreiger",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("c76fbc97-8e5b-3a32-1766-d3d8a5922134"),
                            Email = "Genoveva.Toy59@hotmail.com",
                            FirstName = "Kurtis",
                            LastName = "Johnston",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("499615e1-f7c6-c110-eb41-ebb044c412d8"),
                            Email = "Cyril.Abernathy44@hotmail.com",
                            FirstName = "Coty",
                            LastName = "Lubowitz",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("17577b7b-af78-91d5-697a-789bf0506fc2"),
                            Email = "Sarina.Klein84@yahoo.com",
                            FirstName = "Emmie",
                            LastName = "Dibbert",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("4fac5e66-1450-43f7-b94a-7bb9aa729115"),
                            Email = "Ruthe_Leuschke@yahoo.com",
                            FirstName = "Curt",
                            LastName = "Hoeger",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("cd12f6cc-0d1c-d030-bc67-125128411865"),
                            Email = "Cory98@yahoo.com",
                            FirstName = "Estella",
                            LastName = "Goodwin",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("6f6320be-0061-6073-25e2-835a022927ab"),
                            Email = "Devan_Lynch25@yahoo.com",
                            FirstName = "Walter",
                            LastName = "Rolfson",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("cee419e3-d632-8ac3-cb0f-fca9c06ebbf4"),
                            Email = "Joana_Schaden@yahoo.com",
                            FirstName = "Hoyt",
                            LastName = "Prohaska",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0c48eb8b-e729-337e-86ac-7de68f91f30b"),
                            Email = "Scarlett.Bergnaum36@gmail.com",
                            FirstName = "Joannie",
                            LastName = "Rodriguez",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("a614ad4e-051f-c380-b342-468db660e390"),
                            Email = "Ibrahim.Renner@yahoo.com",
                            FirstName = "Vincenzo",
                            LastName = "Corwin",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("2ceefe3b-063b-9189-0bcc-da39698c66a6"),
                            Email = "Jalyn.Rice@yahoo.com",
                            FirstName = "Silas",
                            LastName = "Walter",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("de608a53-4c46-e96b-8cdd-6b20175487ac"),
                            Email = "Dominic7@yahoo.com",
                            FirstName = "Quinten",
                            LastName = "Von",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("b1f36dbc-d289-bd8a-f47f-d9b1a5aa4abf"),
                            Email = "Wendy_Parker@yahoo.com",
                            FirstName = "Uriah",
                            LastName = "Abshire",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f8942f9c-1ffc-a9e8-6323-22d959b960b9"),
                            Email = "Perry_Kuphal@hotmail.com",
                            FirstName = "Ludie",
                            LastName = "O'Conner",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("9589c16a-9afc-761a-de49-155a3e92c1d4"),
                            Email = "Lemuel.Kiehn74@gmail.com",
                            FirstName = "Magali",
                            LastName = "Kunde",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("197439f4-2ef6-28c6-858d-3a9553adc808"),
                            Email = "Katelyn.Morissette@hotmail.com",
                            FirstName = "Judah",
                            LastName = "Rutherford",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("874b0257-8784-5bfa-e304-0760a65de71a"),
                            Email = "Leonel_Lockman75@gmail.com",
                            FirstName = "Davin",
                            LastName = "Fritsch",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("5775dc78-8902-7878-87c1-f3e33fa3fe93"),
                            Email = "Madisen.Davis@hotmail.com",
                            FirstName = "Yadira",
                            LastName = "Kuvalis",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("c2d455f4-65bb-c019-c901-0baa8404e17a"),
                            Email = "Lupe_OConnell@yahoo.com",
                            FirstName = "Nestor",
                            LastName = "Schowalter",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("8ca871ba-dcf3-171d-8d61-62acb5b5bc21"),
                            Email = "Osvaldo.Cassin@yahoo.com",
                            FirstName = "Franz",
                            LastName = "Friesen",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("8016d4d1-b242-bc20-4547-084abd8ccdec"),
                            Email = "Marina_Barrows@yahoo.com",
                            FirstName = "Isaac",
                            LastName = "Monahan",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("bff2fd2a-d21d-66f5-63cd-ba1ec69cd4da"),
                            Email = "Jermaine96@gmail.com",
                            FirstName = "Mckenzie",
                            LastName = "Denesik",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a3582d66-ea36-9d38-0e3c-5644c0609f73"),
                            Email = "Mozell.Torp56@yahoo.com",
                            FirstName = "Forest",
                            LastName = "Carroll",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("cdfce242-2c57-99b7-d759-ef7952307894"),
                            Email = "Neal.Lynch@yahoo.com",
                            FirstName = "Silas",
                            LastName = "Rempel",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("8b0b1cf3-4974-08b8-1083-f4083ccfb70f"),
                            Email = "Kurt55@gmail.com",
                            FirstName = "Albertha",
                            LastName = "Carter",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("9eb45a6e-019a-278f-01f6-d93a212c258d"),
                            Email = "Cassidy.Hills65@gmail.com",
                            FirstName = "Mallory",
                            LastName = "Shields",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("32e5a87b-56d9-1df9-9a1d-1994196d0ff3"),
                            Email = "Emie.Carter@hotmail.com",
                            FirstName = "Alisa",
                            LastName = "Zboncak",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("91c8655a-3430-02fd-6646-1f59aaf5289f"),
                            Email = "Destany.Jaskolski@yahoo.com",
                            FirstName = "Dudley",
                            LastName = "Weissnat",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("6a6fdb59-5712-8cdb-3660-d7738e68ed65"),
                            Email = "Brannon_Schultz69@gmail.com",
                            FirstName = "Martin",
                            LastName = "Ullrich",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("665f17a6-7963-dd61-4e38-55c593ef0f6a"),
                            Email = "Cecelia.Jerde@hotmail.com",
                            FirstName = "Darrin",
                            LastName = "Bode",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("cbf4ee22-2bb5-91a3-978c-6b407c26d2e7"),
                            Email = "Ollie.Gulgowski8@hotmail.com",
                            FirstName = "Blanche",
                            LastName = "Johns",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0092bb68-29ba-a095-2f44-758496282394"),
                            Email = "Noemi.Weber62@hotmail.com",
                            FirstName = "Jerry",
                            LastName = "Koch",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("47d11ea7-8197-cd61-ad4c-701091dd62d6"),
                            Email = "Kade51@gmail.com",
                            FirstName = "Terence",
                            LastName = "Thompson",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("8672d49a-4ea3-4e7a-429e-120bc35897c2"),
                            Email = "Jordyn13@yahoo.com",
                            FirstName = "Trenton",
                            LastName = "McLaughlin",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a02fada4-f38a-c7fe-b1b6-acc30fda295e"),
                            Email = "Nathanael_Volkman40@hotmail.com",
                            FirstName = "Belle",
                            LastName = "Doyle",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("f7ad481f-6890-a116-21e1-f61fdac34ea0"),
                            Email = "Earl_Haag@hotmail.com",
                            FirstName = "Alf",
                            LastName = "Kovacek",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("b5910a8a-853f-9a4d-e8e9-6baa51d0214d"),
                            Email = "Myriam51@yahoo.com",
                            FirstName = "Rossie",
                            LastName = "Wyman",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("fe7f527f-9a05-6ce2-0f20-6c86d761619c"),
                            Email = "Don.Hansen75@yahoo.com",
                            FirstName = "Raheem",
                            LastName = "Boyer",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("c5b217bf-5940-134b-3335-ed054e944d07"),
                            Email = "Marcelle20@yahoo.com",
                            FirstName = "Coleman",
                            LastName = "Keebler",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("07d76451-0506-03db-05c6-458330a6cfc7"),
                            Email = "Hazle_Ryan12@hotmail.com",
                            FirstName = "Minnie",
                            LastName = "Weimann",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("1d0a58e9-9c16-e349-f273-db81440d2d59"),
                            Email = "Art_Tillman@yahoo.com",
                            FirstName = "Jade",
                            LastName = "Spencer",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d2284369-4b06-1ebb-0f1d-1cadd1e5ef29"),
                            Email = "Stefanie.Trantow@yahoo.com",
                            FirstName = "Jade",
                            LastName = "Stoltenberg",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("968bd376-79bc-1120-ff3e-b4d27477dda7"),
                            Email = "Alfreda.Lockman@hotmail.com",
                            FirstName = "Keshawn",
                            LastName = "O'Kon",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("29525f10-2599-24d8-66c3-5c33c0256195"),
                            Email = "Dashawn_Leannon@yahoo.com",
                            FirstName = "Simeon",
                            LastName = "Bogan",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("367b96c2-b6d2-f574-4a87-855d27f678da"),
                            Email = "Bradley78@yahoo.com",
                            FirstName = "Oliver",
                            LastName = "Tremblay",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("e528dc5b-f6d3-f3d1-aacc-6702a9a151af"),
                            Email = "Xzavier_White@gmail.com",
                            FirstName = "Ralph",
                            LastName = "Dare",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a12cd393-04b0-186a-afe9-dbf68d8f2254"),
                            Email = "Francisco_Lang@yahoo.com",
                            FirstName = "Jacinthe",
                            LastName = "Denesik",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("b361bc3e-aec0-56f2-6e21-52ffca3043a5"),
                            Email = "Edmond_Romaguera14@yahoo.com",
                            FirstName = "Earline",
                            LastName = "Watsica",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("520d8394-7813-a31d-6762-f3a3b65801f6"),
                            Email = "Isai67@hotmail.com",
                            FirstName = "Donny",
                            LastName = "Wyman",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("2240f80c-fe6f-9ae3-a16f-2c2be4035ba8"),
                            Email = "Kayden_Ritchie10@yahoo.com",
                            FirstName = "Abel",
                            LastName = "Cronin",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("b5d341c9-2182-fe0a-be45-1b38fa33697e"),
                            Email = "Letha_Hermiston2@hotmail.com",
                            FirstName = "Wade",
                            LastName = "Hansen",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("b727c608-0aff-4a4c-d1a5-bc10e41e4d21"),
                            Email = "Lera.Hermann61@hotmail.com",
                            FirstName = "Shawna",
                            LastName = "McLaughlin",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("ca64fff6-b77a-a7c0-f27a-5be247be3bcf"),
                            Email = "Deonte_Witting@hotmail.com",
                            FirstName = "Erik",
                            LastName = "Gislason",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("c2eba90a-53ec-9dcf-2d68-080be78057ed"),
                            Email = "Maia45@hotmail.com",
                            FirstName = "Arden",
                            LastName = "Schoen",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("10827083-4d9a-82e0-1b6a-c0d0ccfdba9e"),
                            Email = "Kianna21@gmail.com",
                            FirstName = "Zula",
                            LastName = "Tillman",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("06b0a0d1-4081-ca08-c383-3f7cd1be02e0"),
                            Email = "Arnulfo_Spencer60@hotmail.com",
                            FirstName = "Kristy",
                            LastName = "Ziemann",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("8a32f953-b106-8853-143e-fa9cda00db61"),
                            Email = "Mortimer.Rice41@gmail.com",
                            FirstName = "Isai",
                            LastName = "Fritsch",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("6a403057-4bad-b27e-582e-46d540bdd2ec"),
                            Email = "Joelle.Green@hotmail.com",
                            FirstName = "Rylan",
                            LastName = "Kovacek",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d879ca1a-6f3f-0c86-76b6-af81131d66f2"),
                            Email = "Tremayne.Roob@yahoo.com",
                            FirstName = "Casey",
                            LastName = "Langworth",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("104ad276-b46c-a98f-aa2b-50e3d1a573e8"),
                            Email = "Dennis_Cartwright@hotmail.com",
                            FirstName = "Kyler",
                            LastName = "VonRueden",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("5a8b8d55-b22c-8e80-162a-626c2475a0c1"),
                            Email = "Elmer.Schiller@hotmail.com",
                            FirstName = "Malcolm",
                            LastName = "Klocko",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("5a2a9876-2a2d-2642-f974-bbde29357df7"),
                            Email = "Constance45@gmail.com",
                            FirstName = "Judy",
                            LastName = "Bayer",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("07639d99-f179-d208-6bb4-e393882661ec"),
                            Email = "Alisa.Abbott@gmail.com",
                            FirstName = "Malika",
                            LastName = "Bauch",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("0c3cdf89-7ab6-7093-d4f8-c08fc63aac08"),
                            Email = "Dan.Zemlak@yahoo.com",
                            FirstName = "Alta",
                            LastName = "Oberbrunner",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("07bee05f-1393-d877-0572-7e9ab4fc1bf1"),
                            Email = "Kirstin.Gaylord@hotmail.com",
                            FirstName = "Afton",
                            LastName = "Toy",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d1446a8f-224e-9fa0-6fb7-acd5bb8bdcc1"),
                            Email = "Cleveland64@hotmail.com",
                            FirstName = "Lauren",
                            LastName = "McCullough",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("dd5481cd-e02b-8d1e-bb11-7728cea689e2"),
                            Email = "Arden71@hotmail.com",
                            FirstName = "Louisa",
                            LastName = "Heller",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("7d0efd96-d147-7ef0-17d5-03cdcdc2738f"),
                            Email = "Haley.Reichel73@gmail.com",
                            FirstName = "Franco",
                            LastName = "Wiegand",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("e6dd82a7-1f56-4b88-bf46-2ed1a045e920"),
                            Email = "Sydnee.Block@yahoo.com",
                            FirstName = "Bianka",
                            LastName = "Kreiger",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("2a30649c-808c-0ae3-341f-9f4f1397c0b6"),
                            Email = "Edwina_Schaefer@hotmail.com",
                            FirstName = "Jaida",
                            LastName = "Goyette",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a11a8931-36f9-92a2-7271-4af2ee5dbe3f"),
                            Email = "Bartholome.Blanda33@yahoo.com",
                            FirstName = "Ezekiel",
                            LastName = "Rippin",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("07392842-2793-6bde-56f9-03654111fe7c"),
                            Email = "Dandre.Langworth49@gmail.com",
                            FirstName = "Marianna",
                            LastName = "Schultz",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("76202017-9833-b87b-50b6-0d688bde4a6b"),
                            Email = "Christiana37@hotmail.com",
                            FirstName = "Eduardo",
                            LastName = "Reilly",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("6bbc9805-8314-0b7b-7538-7b06bef52361"),
                            Email = "Verdie_VonRueden53@yahoo.com",
                            FirstName = "Wilber",
                            LastName = "Kreiger",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("b92f47e2-f508-0df5-8171-9adc10a4cd3b"),
                            Email = "Shea_Keebler18@yahoo.com",
                            FirstName = "Juston",
                            LastName = "Schamberger",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("b8312c33-f1ae-bd16-1431-3b4b516d4386"),
                            Email = "Lydia_Schiller50@gmail.com",
                            FirstName = "Angelita",
                            LastName = "Ruecker",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("9b2f20ee-3513-bab5-b6d5-c8c455d37f83"),
                            Email = "Crystel81@yahoo.com",
                            FirstName = "Eloy",
                            LastName = "McDermott",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("0d704adc-7deb-24bc-0d98-bfd1e72201fc"),
                            Email = "Desmond97@gmail.com",
                            FirstName = "Reina",
                            LastName = "Luettgen",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("7c660504-9295-3c2f-9b20-bec9c4a8ce38"),
                            Email = "Franco_Reilly55@hotmail.com",
                            FirstName = "Esteban",
                            LastName = "Kessler",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("165e0b76-93ed-a61a-0709-e6173f8f7b69"),
                            Email = "Adrienne25@gmail.com",
                            FirstName = "Harvey",
                            LastName = "Thiel",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("0bd67f61-55e6-6855-6a82-1e87d025ad8d"),
                            Email = "Delores_Weber@hotmail.com",
                            FirstName = "Leola",
                            LastName = "Dietrich",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("7890533b-99d5-3dc1-2d9b-b56ebd0fbfb2"),
                            Email = "Teagan.Heaney@hotmail.com",
                            FirstName = "Shaylee",
                            LastName = "Weissnat",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("16bf3988-3f7b-3fda-a6c1-cf93c4dd93d0"),
                            Email = "Christian.Stark50@hotmail.com",
                            FirstName = "Thad",
                            LastName = "Bogan",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("7469ea0a-a41b-ba47-33f0-9cd9abc2eec1"),
                            Email = "Carolyn16@yahoo.com",
                            FirstName = "Natasha",
                            LastName = "Walsh",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("9a8ffcdc-ec64-6948-2bb3-705470cb8a1c"),
                            Email = "Mellie_Walsh91@hotmail.com",
                            FirstName = "Chanelle",
                            LastName = "Weimann",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("d477fa73-3653-131c-7f97-1f15ad5646a7"),
                            Email = "Marta.Swaniawski@hotmail.com",
                            FirstName = "Ansel",
                            LastName = "Casper",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("5c52b8de-f4ea-e7e5-702e-f0f1d195d77d"),
                            Email = "Bernadine.Weber45@hotmail.com",
                            FirstName = "Arjun",
                            LastName = "Quigley",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("1d48c345-d2cd-5023-39f5-9be3c0298ab2"),
                            Email = "Cassie.Klein90@hotmail.com",
                            FirstName = "Linda",
                            LastName = "Erdman",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("765e58fd-d7d2-cede-12a4-309dcaa25bcc"),
                            Email = "Arnoldo99@gmail.com",
                            FirstName = "Raphaelle",
                            LastName = "Littel",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("5a623381-f41d-266f-71a3-d07ac5da661e"),
                            Email = "Sienna.Fisher79@hotmail.com",
                            FirstName = "Lucie",
                            LastName = "Jast",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("fe3db399-e09a-4069-f7f4-9f7483b01d35"),
                            Email = "Felicity.Beier91@gmail.com",
                            FirstName = "Russel",
                            LastName = "Murray",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("92e6857f-6c0c-5fc5-3684-403128d6c266"),
                            Email = "Leland_Muller84@yahoo.com",
                            FirstName = "Bo",
                            LastName = "Fritsch",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("2f46e850-9242-0ced-7c1b-5b83aeea87da"),
                            Email = "Toni32@gmail.com",
                            FirstName = "Winnifred",
                            LastName = "Gottlieb",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("e138a76c-d76a-2046-5742-bc847f30f4f2"),
                            Email = "Karelle_Davis17@hotmail.com",
                            FirstName = "Kory",
                            LastName = "Goldner",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("38eb94ec-4cb2-926e-e2c3-9a590ba1a5d4"),
                            Email = "Queen.Hills7@gmail.com",
                            FirstName = "Raul",
                            LastName = "Gibson",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("9b36dd89-89fc-541c-837e-435ae8a5f64e"),
                            Email = "Marielle54@gmail.com",
                            FirstName = "Antonietta",
                            LastName = "Feeney",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("20b72de6-5ab6-af91-93fe-296e37f6e539"),
                            Email = "Tomasa19@gmail.com",
                            FirstName = "Reagan",
                            LastName = "Halvorson",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("be11df75-fe77-41a0-5930-b5cfd1fc9d29"),
                            Email = "Joshua3@yahoo.com",
                            FirstName = "Estelle",
                            LastName = "Kuvalis",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("92db33b6-61bf-6ca3-dc30-aad648d33795"),
                            Email = "Abdullah.Ferry@hotmail.com",
                            FirstName = "Otha",
                            LastName = "Anderson",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("ce365f68-67b2-ed0a-c915-0744220e81f8"),
                            Email = "Darrel5@yahoo.com",
                            FirstName = "Geovany",
                            LastName = "Fritsch",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("948c315b-0f72-a0ba-cb59-2a602ad4b975"),
                            Email = "America67@gmail.com",
                            FirstName = "Christelle",
                            LastName = "Mann",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("f7791c66-c623-a031-7e1c-7381da767bb9"),
                            Email = "Hallie87@gmail.com",
                            FirstName = "Meredith",
                            LastName = "Prosacco",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("937b7d8f-acba-684d-bd3c-2d5596c27c04"),
                            Email = "Leonora_Runte50@yahoo.com",
                            FirstName = "Elaina",
                            LastName = "Jacobson",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("7964d853-6bab-4f45-c068-a64b9de6d1cf"),
                            Email = "Betty55@yahoo.com",
                            FirstName = "Montana",
                            LastName = "Kutch",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("3e5a9f75-56bf-e357-cb52-67d4e9ee12d1"),
                            Email = "Brennan_Wintheiser@yahoo.com",
                            FirstName = "Nathaniel",
                            LastName = "Kohler",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("75573e0f-66fc-301a-3f78-040b11078f6a"),
                            Email = "Raheem.Runte@gmail.com",
                            FirstName = "Christopher",
                            LastName = "Pouros",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("2061ccb0-3e4c-bc15-14b6-2f81ffe1e665"),
                            Email = "Filiberto_Berge@gmail.com",
                            FirstName = "Abbigail",
                            LastName = "Armstrong",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("13496b76-4138-1223-583b-c42f04fae301"),
                            Email = "Rowland90@yahoo.com",
                            FirstName = "Marcelo",
                            LastName = "Funk",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("48121adb-7568-a931-0c81-a9e1f40283d3"),
                            Email = "Jacey_OKeefe@gmail.com",
                            FirstName = "Anabelle",
                            LastName = "Hegmann",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("a20d9352-650f-6908-0019-371e2edbaae3"),
                            Email = "Jonatan_Kilback80@yahoo.com",
                            FirstName = "Nelle",
                            LastName = "Corwin",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("e5bbc724-12a7-b824-d4f6-d4688e99a678"),
                            Email = "Moses66@gmail.com",
                            FirstName = "Fidel",
                            LastName = "Windler",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("9301b844-ecde-864f-abde-eb9e4d845807"),
                            Email = "Aurelie_Funk@yahoo.com",
                            FirstName = "Kallie",
                            LastName = "Blanda",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("2210097c-9631-805f-0f49-a0ef1191dae7"),
                            Email = "Sterling85@hotmail.com",
                            FirstName = "Holden",
                            LastName = "Walker",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("feb8d388-d34a-c99c-3c7f-16d4dc2d5415"),
                            Email = "Alexandrine.Aufderhar@hotmail.com",
                            FirstName = "Evan",
                            LastName = "Willms",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("873d728b-cbbf-74d2-dd54-995edd61353b"),
                            Email = "Laney.Kilback@yahoo.com",
                            FirstName = "Merritt",
                            LastName = "Ebert",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("4331a6f8-2879-1ed7-dd37-72d795140a70"),
                            Email = "Noble_McLaughlin@hotmail.com",
                            FirstName = "Ocie",
                            LastName = "Kunde",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("0d565335-64b6-8607-67c4-8f189a8efab5"),
                            Email = "Taurean31@yahoo.com",
                            FirstName = "Lenna",
                            LastName = "Collier",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d7e441cc-830f-02e5-6d13-0e26d2c96879"),
                            Email = "Marcellus.Schmidt@gmail.com",
                            FirstName = "Estrella",
                            LastName = "Hegmann",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("180a41a7-9276-d62f-acbc-41757f2f76e3"),
                            Email = "Queenie.Vandervort@yahoo.com",
                            FirstName = "Jazmyn",
                            LastName = "Cremin",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("01750712-d4ee-db14-6bc6-2fce79cc8bdb"),
                            Email = "Dora_Heller77@yahoo.com",
                            FirstName = "Lydia",
                            LastName = "Jast",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("46f8f28c-9d4f-5dd3-5605-6f1c2de7d8a8"),
                            Email = "Terence87@gmail.com",
                            FirstName = "Tremayne",
                            LastName = "Schamberger",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("5b47a1cf-2acd-0d20-758b-62e11c941b28"),
                            Email = "Damion_Frami91@hotmail.com",
                            FirstName = "Velma",
                            LastName = "Mohr",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("40e8226d-cc00-e122-f776-ad5678902be5"),
                            Email = "Ashley_Pfannerstill95@hotmail.com",
                            FirstName = "Julia",
                            LastName = "Hoppe",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("4a4638a4-10e4-f7eb-ba5f-0837cc75bf40"),
                            Email = "Roxane.Ondricka64@yahoo.com",
                            FirstName = "Mabel",
                            LastName = "McDermott",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("cb1517bb-e1aa-fa50-af5b-94db961366c2"),
                            Email = "Cristian51@hotmail.com",
                            FirstName = "Michaela",
                            LastName = "Rempel",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("b367f544-be80-59c0-4f69-29f8d52b0f7d"),
                            Email = "Orlo_Cremin@yahoo.com",
                            FirstName = "Bulah",
                            LastName = "Kautzer",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("2573aab7-d4ae-2632-e632-87b47a9d79f1"),
                            Email = "Carmella.Hayes@gmail.com",
                            FirstName = "Oswald",
                            LastName = "Becker",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("716bb3ae-1877-dfb7-8b55-fcd54a9baa7a"),
                            Email = "Rupert25@gmail.com",
                            FirstName = "Cynthia",
                            LastName = "Dach",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("ef7e2bc2-3dd8-4927-bd40-76fb68c0aecd"),
                            Email = "Braxton35@gmail.com",
                            FirstName = "Anita",
                            LastName = "Bruen",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("e7f51190-4a5b-538e-af51-ae4c99c7064d"),
                            Email = "Donny32@hotmail.com",
                            FirstName = "Rollin",
                            LastName = "Windler",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("fc274454-dd32-1e7a-847e-5ec74840ee73"),
                            Email = "Lorena.Langworth@yahoo.com",
                            FirstName = "Madisyn",
                            LastName = "Cole",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("edf7dba1-9c8c-e1db-ff7f-9316229221d2"),
                            Email = "Scotty77@hotmail.com",
                            FirstName = "Consuelo",
                            LastName = "Hane",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0058a4c5-fa63-f163-1074-5a56e68d92e7"),
                            Email = "Aisha.Lemke71@hotmail.com",
                            FirstName = "Millie",
                            LastName = "Kuhic",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("9a824079-4a18-d662-0a28-e844da7e051b"),
                            Email = "Unique.McLaughlin@yahoo.com",
                            FirstName = "Lemuel",
                            LastName = "Senger",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("77eb78e0-3f3c-52ed-3afe-e9b9e156f729"),
                            Email = "Roy58@hotmail.com",
                            FirstName = "Heloise",
                            LastName = "Auer",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d10badc2-e6a4-8d38-f685-baa05eea99ca"),
                            Email = "Reba_Ortiz79@hotmail.com",
                            FirstName = "Mina",
                            LastName = "Bergnaum",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("0f494083-52e4-b03c-edb5-8e331bae54c5"),
                            Email = "Lula.Morissette10@gmail.com",
                            FirstName = "Adan",
                            LastName = "Gerlach",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("eb99142a-7669-c073-c320-a5ef7e12327d"),
                            Email = "Jacey_Herzog@gmail.com",
                            FirstName = "Britney",
                            LastName = "Murazik",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("dd893817-b7af-33b8-62fd-ba3da3c5833f"),
                            Email = "Ariane_Bartell66@gmail.com",
                            FirstName = "Keven",
                            LastName = "Kuhlman",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("d759671d-7bdc-2d0b-e4d4-30ed96110c67"),
                            Email = "Xavier_Schulist80@hotmail.com",
                            FirstName = "Adah",
                            LastName = "Ortiz",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("59c723ef-4006-d85b-b391-4f5e5b8582af"),
                            Email = "Linda_Welch63@hotmail.com",
                            FirstName = "Jo",
                            LastName = "Larkin",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("585c493d-4335-6b3c-e1ed-5744d3de93d5"),
                            Email = "Lee.Gottlieb@yahoo.com",
                            FirstName = "Roma",
                            LastName = "MacGyver",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("3a1ce4a8-a49a-c16a-7b34-c9f6fe7f7d4e"),
                            Email = "Stephan74@hotmail.com",
                            FirstName = "Althea",
                            LastName = "King",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a13d7d5d-8ee1-271c-425e-b0512602d13d"),
                            Email = "Monique94@yahoo.com",
                            FirstName = "Anastacio",
                            LastName = "Fisher",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("16a83265-6f9b-3dd3-a63b-dc1d67c9e0ec"),
                            Email = "Riley81@yahoo.com",
                            FirstName = "Gabriella",
                            LastName = "Davis",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("95153d21-9ea2-c0cb-a6a8-3bafe6068cd2"),
                            Email = "Ken13@hotmail.com",
                            FirstName = "Pattie",
                            LastName = "Williamson",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("7387dbb4-37e8-39c4-0a97-f45d593e9b08"),
                            Email = "Parker_Keeling@gmail.com",
                            FirstName = "Magali",
                            LastName = "Lubowitz",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("5d15e115-3b81-6dec-675c-e0c61658d76e"),
                            Email = "Jude2@hotmail.com",
                            FirstName = "Deven",
                            LastName = "Spencer",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("087ba2d7-173c-832a-d576-5d062167b7cf"),
                            Email = "Madelyn57@yahoo.com",
                            FirstName = "Garrick",
                            LastName = "Kohler",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("8dda0845-b78d-e7fe-69c9-85dfc0e43150"),
                            Email = "Monserrat13@yahoo.com",
                            FirstName = "Bobbie",
                            LastName = "Torphy",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("8ba4d549-7b38-03ed-b063-c3333c9df51d"),
                            Email = "Paolo_Koelpin64@hotmail.com",
                            FirstName = "Harmony",
                            LastName = "Beier",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("e301caa6-1c51-bb74-5e43-b81273afeddb"),
                            Email = "Delphine74@yahoo.com",
                            FirstName = "Art",
                            LastName = "Greenfelder",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("338528d3-9af4-c671-de36-91b1eb205f47"),
                            Email = "Alexis.McDermott20@gmail.com",
                            FirstName = "Emilie",
                            LastName = "Greenfelder",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("b1aa5f7d-57a4-3593-9a0f-299740c7c3d2"),
                            Email = "Verner.Grant@hotmail.com",
                            FirstName = "Pierre",
                            LastName = "Kihn",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("3485d116-293b-23c8-bf83-763bc61539de"),
                            Email = "Lola.Schuster@hotmail.com",
                            FirstName = "Torrey",
                            LastName = "Stoltenberg",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("d74b871a-a8c7-8d73-fcdb-9bd3d15ef971"),
                            Email = "Dave_Bogan81@gmail.com",
                            FirstName = "Raymond",
                            LastName = "King",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("9ec01e5e-9851-c366-d519-b4ddf15c160f"),
                            Email = "Emiliano60@gmail.com",
                            FirstName = "Bart",
                            LastName = "Bogisich",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("d731c9df-5f52-7b91-6fdd-6889b3eeab43"),
                            Email = "Bell_Hintz37@gmail.com",
                            FirstName = "Celia",
                            LastName = "Hegmann",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("204a67ac-9362-7e51-3ebf-88678e707588"),
                            Email = "Rolando_Barrows@hotmail.com",
                            FirstName = "Ron",
                            LastName = "Sawayn",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("105644a7-3c5b-734c-8816-a5f7475a0c49"),
                            Email = "Porter_Bode44@gmail.com",
                            FirstName = "Alene",
                            LastName = "Denesik",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("42240cbc-34b4-6c50-b779-1d3d40230273"),
                            Email = "Colleen_Bartell70@gmail.com",
                            FirstName = "Daren",
                            LastName = "Connelly",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("cbe881dd-ca70-b79d-8a9e-2f2731d4e155"),
                            Email = "Burley26@gmail.com",
                            FirstName = "Joseph",
                            LastName = "Gibson",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("2efe0dbb-08d3-2e7c-c277-d6b267a146ae"),
                            Email = "Pink.Kovacek85@hotmail.com",
                            FirstName = "Amari",
                            LastName = "Hessel",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("fdb0f276-be73-9a06-7710-63cc6ee38122"),
                            Email = "Cathrine38@hotmail.com",
                            FirstName = "Noe",
                            LastName = "Brown",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("20866f32-9e62-296f-f498-5c15cb314fb9"),
                            Email = "Cyril.Wilderman88@gmail.com",
                            FirstName = "Dario",
                            LastName = "Upton",
                            Role = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
