services:
  master_db:
    container_name: master_db
    image: postgres:15-alpine
    ports:
      - "3000:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_data_master:/var/lib/postgresql/data
      - ./scripts/master/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - postgres_ha_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  slave_db1:
    container_name: slave_db1
    image: postgres:15-alpine
    ports:
      - "3001:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - REPLICATION_SLOT=slave_1
      - PGPASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data_slave_1:/var/lib/postgresql/data
      - ./scripts/slave/entrypoint.sh:/entrypoint.sh
    networks:
      - postgres_ha_network
    command: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      master_db:
        condition: service_healthy

  slave_db2:
    container_name: slave_db2
    image: postgres:15-alpine
    ports:
      - "3002:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - REPLICATION_SLOT=slave_2
      - PGPASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data_slave_2:/var/lib/postgresql/data
      - ./scripts/slave/entrypoint.sh:/entrypoint.sh
    networks:
      - postgres_ha_network
    command: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      master_db:
        condition: service_healthy

  pgpool:
    image: bitnami/pgpool:4
    ports:
      - 4000:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:master_db:5432,1:slave_db1:5432,2:slave_db2:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=121002
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=121002
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=121002
    networks:
      - postgres_ha_network
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgres_ha_network:
    driver: bridge

volumes:
  postgres_data_master:
  postgres_data_slave_1:
  postgres_data_slave_2: