apiVersion: v1
kind: Service
metadata:
  name: cpm-idp-service
spec:
  type: NodePort  # Change from NodePort to LoadBalancer
  selector:
    app: cpm-idp-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31847
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpm-idp-service
  labels:
    app: cpm-idp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpm-idp-service
  template:
    metadata:
      labels:
        app: cpm-idp-service
    spec:
      containers:
      - name: cpm-idp-service
        image: ghcr.io/weed1210/cpm-identity-service:latest
        env:
        - name: SERVICE_NAME
          value: Identity
        - name: Keycloak__realm
          value: cpm
        - name: Keycloak__auth-server-url
          value: http://192.168.49.2:31284
        - name: Keycloak__ssl-required
          value: none
        - name: Keycloak__resource
          value: security-admin-console
        - name: Keycloak__verify-token-audience
          value: "false"
        - name: Keycloak__credentials__secret
          value: s6FokfrwAUixEVjzTHMBoBFxNF3niwva
        - name: Keycloak__confidential-port
          value: "0"
      imagePullSecrets:
      - name: ghcr