apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpm-ui-deployment
  labels:
    app: com-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpm-ui
  template:
    metadata:
      labels:
        app: cpm-ui
    spec:
      containers:
      - name: cpm-ui
        image: ghcr.io/weed1210/cpm-ui:latest
      imagePullSecrets:
      - name: regcred