apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort  # Change from NodePort to LoadBalancer
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31284