name: Publish Common NuGet Packages

on:
  push:
    branches: ["main"]
    paths:
      - "sevices/Common/**"
      - ".github/workflows/common-nuget.yaml"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/vytrancao/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.TOKEN }}

      - name: Restore Dependencies
        run: dotnet restore Common.sln

      - name: Build Solution
        run: dotnet build Common.sln --configuration Release --no-restore

      - name: Pack NuGet Packages
        run: dotnet pack Common.sln --configuration Release --output nupkgs --no-restore --no-build

      - name: Publish to GitHub Packages
        run: dotnet nuget push "nupkgs/*.nupkg" --source "github" --api-key ${{ secrets.TOKEN }} --skip-duplicate
